#!/bin/bash
# Fetch secrets from aws secrets manager
# Note: only works with the one pushed by CDK/RDS; others may not
#       match the same schema and will throw an error

AWS_PROFILE=blog

get() {
    aws --profile $AWS_PROFILE secretsmanager get-secret-value --secret-id $1 \
        | jq -r .SecretString | jq -r .password
}
secrets=($(aws --profile $AWS_PROFILE secretsmanager list-secrets | jq -r '.["SecretList"][].Name'))
for secret in ${secrets[@]}; do
    _secret=$(get $secret)
    echo -e "$secret\t=>\t$_secret"
done
